[2020-01-17 11:01:31,262] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: getGmailAttachments.hello_task 2020-01-15T12:00:00+00:00 [queued]>
[2020-01-17 11:01:31,285] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: getGmailAttachments.hello_task 2020-01-15T12:00:00+00:00 [queued]>
[2020-01-17 11:01:31,286] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-01-17 11:01:31,286] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1
[2020-01-17 11:01:31,287] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-01-17 11:01:31,315] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): hello_task> on 2020-01-15T12:00:00+00:00
[2020-01-17 11:01:31,319] {{standard_task_runner.py:52}} INFO - Started process 28367 to run task
[2020-01-17 11:01:31,385] {{logging_mixin.py:112}} INFO - [2020-01-17 11:01:31,385] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/email.py
[2020-01-17 11:01:31,404] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: getGmailAttachments.hello_task 2020-01-15T12:00:00+00:00 [running]> 7f68746faaa4
[2020-01-17 11:01:31,420] {{python_operator.py:105}} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=getGmailAttachments
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-15T12:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-15T12:00:00+00:00
[2020-01-17 11:01:32,533] {{taskinstance.py:1088}} ERROR - LOGIN command error: BAD [b'Too many arguments provided 2mb70538751jao']
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 955, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/email.py", line 16, in fetchGmailAttachments
    typ, accountDetails = imapSession.login(userName, passwd)
  File "/usr/local/lib/python3.7/imaplib.py", line 596, in login
    typ, dat = self._simple_command('LOGIN', user, self._quote(password))
  File "/usr/local/lib/python3.7/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/local/lib/python3.7/imaplib.py", line 1027, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.IMAP4.error: LOGIN command error: BAD [b'Too many arguments provided 2mb70538751jao']
[2020-01-17 11:01:32,536] {{taskinstance.py:1119}} INFO - Marking task as FAILED.
[2020-01-17 11:01:41,226] {{logging_mixin.py:112}} INFO - [2020-01-17 11:01:41,226] {{local_task_job.py:103}} INFO - Task exited with return code 1
